language: php
php:
  - 7.2

before_script:
  - composer install --no-interaction

services:
  - mysql

before_install:
  - mysql -e 'source hasdbchanged/sql/snapshotstructure.sql;'
  - mysql -e 'source hasdbchanged/test/createtable.sql;'
