language: php
php:
  - 7.2

before_script:
  - composer install --no-interaction

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE toolboxphp_test; USE toolboxphp_test;'
  - mysql -e 'source hasdbchanged/sql/snapshotstructure.sql;'
