<?php
/**
 * @compay self
 * @author Raymond Byczko
 * @filesource CYearTest.php
 * @file CYearTest.php
 * @start_date 2014-06-13 June 13
 */

require_once '../CYear.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-13 at 15:02:28.
 */
class CYearTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CYear
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CYear;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers CYear::isLeapYear
     * @todo   Implement testIsLeapYear().
     */
    public function testIsLeapYear() {
        $result1900 = $this->object->isLeapYear(1900);
        $this->assertTrue($result1900 == true);
        $result1901 = $this->object->isLeapYear(1901);
        $this->assertTrue($result1901 == true);
    }

    /**
     * @covers CYear::daysToDate
     * @todo   Implement testDaysToDate().
     */
    public function testDaysToDate() {
        $numDays1 = $this->object->daysToDate(1, 15, 1900);
        $this->assertTrue($numDays1 == 15);
        $numDays2 = $this->object->daysToDate(2, 1, 1900);
        $this->assertTrue($numDays2 == 32);
    }
    
    public function testDays1900ToDate()
    {
        $numDays1 = $this->object->days1900ToDate(1, 10, 1900);
        $this->assertTrue($numDays1 == 10);
        $numDays2 = $this->object->days1900ToDate(1, 11, 1901);
        $this->assertTrue($numDays2 == 377); 
    }

}
